version: "3.8"
services:
   vote:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - REDIS_HOST=${REDIS_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./Stage-1/vote/:/usr/local/app
    ports: 
    - '8080:80'
volumes:
  vote_data: